FROM bitnami/spark:3.5.0

USER root

RUN apt-get -y update && apt-get -y install curl

RUN apt-get update \
    && apt-get install -y --no-install-recommends default-jdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/default-java
ENV PATH="${JAVA_HOME}/bin:${PATH}"


RUN curl -O https://archive.apache.org/dist/hadoop/common/hadoop-3.3.1/hadoop-3.3.1.tar.gz \
    && tar -xzvf hadoop-3.3.1.tar.gz -C /usr/local/ \
    && rm hadoop-3.3.1.tar.gz
ENV HADOOP_HOME=/usr/local/hadoop-3.3.1
ENV HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop
ENV PATH="${HADOOP_HOME}/bin:${PATH}"

# RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar \
#     -P opt/bitnami/sp/jars/

# Copy configuration files
COPY config/ /opt/bitnami/spark/conf/

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
