name: CI

on:
  push:
    paths:
      - 'dags/**' # Trigger only when changes occur in the "dags/" folder

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Test PySpark scripts
      run: |
        pytest tests/test_spark_scripts.py
